# Generated by Django 4.1.2 on 2023-02-02 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='crypto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_name', models.CharField(max_length=120)),
                ('price', models.FloatField()),
                ('hourly_change', models.CharField(max_length=120)),
                ('daily_change', models.CharField(max_length=120)),
            ],
        ),
    ]
